test: implement test for extract_prefix_and_root
starknet-id/api.starknet.id pull request #112
Opened 2024-11-23 01:54 UTC by mayasimi

Closes #105 

Ready for review

2024-11-23 17:25 UTC, Marchand-Nicolas requested changes

2024-11-23 17:25 UTC, Marchand-Nicolas commented on src/utils.rs
> +#[cfg(test)]
Please put it in src/tests/utils.rs (you'll have to create the folders)

2024-11-24 14:04 UTC, mayasimi commented
@Marchand-Nicolas 

implemented the separation of test in a different file. ready for review

test passed:

![Screenshot from 2024-11-24 15-03-38](https://github.com/user-attachments/assets/10d5d5db-a595-4888-8020-81c7f192da21)

2024-11-25 09:05 UTC, mayasimi commented
@Marchand-Nicolas ready for review

2024-11-25 13:01 UTC, Marchand-Nicolas approved these changes
I made a little fix, now lgtm! Well done it's working perfectly :)

2024-11-25 13:01 UTC, Marchand-Nicolas commented on src/utils.rs
> +git
I guess you forgot to remove that

2024-11-25 13:02 UTC, merged