Write the readme
starknet-id/api.starknet.id pull request #115
Opened 2024-11-24 08:27 UTC by Benjtalkshow

Closes #102

2024-11-24 08:28 UTC, Benjtalkshow commented
@Marchand-Nicolas 
Please Review

2024-11-24 10:31 UTC, Marchand-Nicolas requested changes

2024-11-24 10:31 UTC, Marchand-Nicolas commented on README.md
> +⚠️ **WARNING**: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.
You can remove this warning, because it is specific to OD

2024-11-24 10:31 UTC, Marchand-Nicolas commented on README.md
> +The StarknetID API is designed to handle identity-related operations on the StarkNet blockchain. It provides a robust interface for managing and querying StarkNet identities, making it easier to inte
You can remove the first sentence (The StarknetID API is designed to handle identity-related operations on the StarkNet blockchain.)

2024-11-24 10:31 UTC, Marchand-Nicolas commented on README.md
> +StarknetID API is a Rust-based service that provides API endpoints for interacting with StarkNet identities. This API serves as the backend infrastructure for StarkNet identity management and resolut
You can remove this, because it's redundant with the description

2024-11-24 13:09 UTC, Benjtalkshow commented
@Marchand-Nicolas Done Ser

2024-11-25 12:17 UTC, Marchand-Nicolas approved these changes
Lgtm well done!

2024-11-25 12:17 UTC, merged