feat: Implement WatchTower
starknet-id/api.starknet.id pull request #116
Opened 2024-11-26 04:21 UTC by TropicalDog17

Closes #104

2024-11-26 19:01 UTC, Marchand-Nicolas requested changes
Just one little change

2024-11-26 19:01 UTC, Marchand-Nicolas commented on src/main.rs
> +    logger.warning(format!(
Please remove the warning and the severe, we just want to keep the info one

2024-11-27 10:35 UTC, TropicalDog17 commented on src/main.rs
> +    logger.warning(format!(
Should I remove the logger.warning in `main.rs` or get rid of the `Warning` and `Severe` variant? @Marchand-Nicolas?

2024-11-27 10:37 UTC, Marchand-Nicolas commented on src/main.rs
> +    logger.warning(format!(
@TropicalDog17 Remove logger.warning & logger.servere in main.rs. But we keep the warning & severe variants

2024-11-27 13:25 UTC, Marchand-Nicolas approved these changes
Lgtm!

2024-11-27 13:25 UTC, merged