Fix: Reinforce the WatchTower implementation #121
starknet-id/api.starknet.id pull request #127
Opened 2024-12-13 18:46 UTC by ryzen-xp

close: #121

2024-12-13 18:52 UTC, ryzen-xp commented
@Marchand-Nicolas  Sir Please review th PR

2024-12-14 11:05 UTC, Marchand-Nicolas requested changes

2024-12-14 11:05 UTC, Marchand-Nicolas commented on src/endpoints/campaigns/get_free_domain.rs
> +    let logger = Logger::new(&conf.watchtower);
We don't want to have multiple logger instance. You can use state.logger instead (which returns the logger instance created in main.rs)

2024-12-14 11:06 UTC, Marchand-Nicolas requested changes

2024-12-14 11:06 UTC, Marchand-Nicolas commented on src/main.rs
> +    // println!("starknetid_server: starting v{}", env!("CARGO_PKG_VERSION"));
Don't comment this line. Instead, move it after the logger definition, and use it

2024-12-14 19:22 UTC, ryzen-xp commented
@Marchand-Nicolas  Sir  please check  again my PR  ,

2024-12-14 22:23 UTC, Marchand-Nicolas requested changes

2024-12-14 22:23 UTC, Marchand-Nicolas commented on src/resolving.rs
> +                if let Ok(resolver) = document.get_str("resolver") {
Why this change ?

2024-12-15 05:37 UTC, ryzen-xp commented on src/resolving.rs
> +                if let Ok(resolver) = document.get_str("resolver") {
sorry sir I did not notice

2024-12-15 05:38 UTC, ryzen-xp commented
@Marchand-Nicolas Sir please check again my PR .

2024-12-15 11:14 UTC, Marchand-Nicolas approved these changes
Lgtm!

2024-12-15 11:14 UTC, merged

2024-12-15 11:21 UTC, ryzen-xp commented
Thank You Sir @Marchand-Nicolas