Feat: get_altcoin_quote endpoint
starknet-id/api.starknet.id pull request #58
Opened 2024-03-06 08:40 UTC by irisdv

2024-03-08 16:28 UTC, Th0rgal approved these changes

2024-03-08 16:41 UTC, Th0rgal requested changes
This code looks good to me, I don't see any reason it would fail. However, I think we need to be very careful because an issue with it could cause a lot of damage (if someone can generate signatures allowing him to buy domains for 0 STRK for example). Because we rely on the AVNU API, I would like if you could change the configuration to allow us to add some security margin. Instead of just having a token_support with generic data, I would like something like this:

```toml
[altcoins]
private_key = "123"

# Ethereum (ETH) is not enabled for the moment as it is already supported by default buy.
# [altcoins.ETH]
# address = "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
# min_price = 1
# max_price = 1
# decimals = 18
# max_quote_validity = 3600 # in seconds for ETH

[altcoins.STRK]
address = "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
min_price = 500
max_price = 5000
decimals = 18
max_quote_validity = 300 # it moves faster so we reduce the quote validity

[altcoins.USDC]
address = "0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8"
min_price = 2000
max_price = 10000
decimals = 6 # not sure really
max_quote_validity = 600

[altcoins.USDT]
address = "0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8"
min_price = 2000
max_price = 10000
decimals = 18
max_quote_validity = 600
```

Finally, could you please move the endpoints out of the avnu folder, because it is not really an avnu feature (we could use another source for pricing) and it is not the path chosen in the axum macro.

2024-03-08 16:41 UTC, Th0rgal commented on src/endpoints/avnu/get_altcoin_quote.rs
> +                            let message_hash = pedersen_hash(
I think USDC doesn't work with 18 decimals, you should use a value chosen in config

2024-03-12 14:56 UTC, irisdv commented on src/endpoints/get_altcoin_quote.rs
> +                            if quote < altcoin_data.min_price as f64
Actually I return an error if the quote is below the `min_price`, or higher than the `max_price`. I continue if `quote >= min_price`. I understood the min and max_price in the config as being the range of the quotation, am I right ?

2024-03-13 10:36 UTC, Th0rgal approved these changes

2024-03-13 10:36 UTC, merged