feat: add ccip support to domain_to_addr
starknet-id/api.starknet.id pull request #73
Opened 2024-04-15 08:15 UTC by irisdv

Close #72

2024-04-17 15:59 UTC, Th0rgal requested changes
Great job, it's going to be very cool. Could you please add the relevant index to the indexer and may be update the docs to warn the users about the 10min warning? On this pr only a small naming change and that lgtm

2024-04-17 15:59 UTC, Th0rgal commented on src/resolving.rs
> +pub fn is_offchain_resolver(
I think get_offchain_resolver would make more sense because you get an Option and not a boolean

2024-04-18 09:03 UTC, irisdv commented
I updated the `update_offchain_resolvers` function to support multiple `uri`, and multiple `domains` that could have the same resolver contract.

2024-04-18 10:06 UTC, Th0rgal approved these changes
lgtm

2024-04-18 10:06 UTC, merged